name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - requests=2.24.0
  - pip=20.3.3
  - python=3.8
  - pip:
      - wandb==0.10.21
      - protobuf==3.20.1
      - watchdog==2.0.0
